 version: '3'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    restart: always
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - 10051:10051
    networks:
      - zabbix_network
    depends_on:
      - db
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    hostname: zabbix-server

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    restart: always
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root_password
      - ZBX_SERVER_HOST=zabbix-server
    ports:
      - 80:8080
    networks:
      - zabbix_network
    depends_on:
      - db
    hostname: zabbix-web

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - zabbix_network
    hostname: mysql-server

volumes:
  zabbix_server_data:
  db_data:

networks:
  zabbix_network:
